import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Create & Vote on Polls | Engage in Real-Time Discussions</title>
        <meta
          name="description"
          content="Create polls, vote, and share opinions on trending topics. Join thousands of users in debates across categories like tech, sports, entertainment, and politics. Start now!"
        />
        <meta
          name="keywords"
          content="online polls, vote online, create poll, poll maker, opinion polls, real-time voting, surveys, best poll platform"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
